when@prod:
    storefront:
        # Uncomment all to enable soft purge
        # http_cache:
        # stale_while_revalidate: 300
        # stale_if_error: 3600
        reverse_proxy:
            enabled: true
            fastly:
                enabled: true
                api_key: '%env(FASTLY_API_TOKEN)%'
                service_id: '%env(FASTLY_SERVICE_ID)%'
                # Uncomment to enable soft purge
                # soft_purge: '1'
