# yaml-language-server: $schema=https://raw.githubusercontent.com/shopware/shopware/trunk/config-schema.json

shopware:
    http_cache:
        # Uncomment all to enable soft purge
        # Allow to serve the out-dated cache for 300 seconds
        # stale_while_revalidate: 300
        # Allow to serve the out-dated cache for an hour if the origin server is offline
        # stale_if_error: 3600
        reverse_proxy:
            enabled: true
            fastly:
                enabled: true
                api_key: '%env(FASTLY_API_TOKEN)%'
                service_id: '%env(FASTLY_SERVICE_ID)%'
                soft_purge: '1'
