# yaml-language-server: $schema=https://raw.githubusercontent.com/shopware/shopware/trunk/config-schema.json

parameters:
    env(CONTAINER_FILESYSTEM_PRIVATE_BUCKET): ""
    env(CONTAINER_FILESYSTEM_PUBLIC_BUCKET): ""
    env(CONTAINER_FILESYSTEM_PUBLIC_URL): ""
    env(CONTAINER_FILESYSTEM_REGION): ""
    env(CONTAINER_FILESYSTEM_ENDPOINT): ""
    env(CONTAINER_CACHE_URL): "redis://localhost:6379"
shopware:
    api:
        jwt_key:
            use_app_secret: true
    admin_worker:
        enable_admin_worker: false
        enable_notification_worker: false
        enable_queue_stats_worker: false
    deployment:
        cluster_setup: true
    auto_update:
        enabled: false
    store:
        frw: false
    mail:
        update_mail_variables_on_send: false
    cache:
        tagging:
            each_snippet: true
            each_config: false
            each_theme_config: false
    increment:
        user_activity:
            type: array
        message_queue:
            type: array
    filesystem:
        private:
            type: "amazon-s3"
            visibility: "private"
            config:
                bucket: "%env(CONTAINER_FILESYSTEM_PRIVATE_BUCKET)%"
                region: "%env(CONTAINER_FILESYSTEM_REGION)%"
                endpoint: "%env(CONTAINER_FILESYSTEM_ENDPOINT)%"
                use_path_style_endpoint: true
        public: &public_bucket
            type: "amazon-s3"
            url: "%env(CONTAINER_FILESYSTEM_PUBLIC_URL)%"
            visibility: "public"
            config:
                bucket: "%env(CONTAINER_FILESYSTEM_PUBLIC_BUCKET)%"
                region: "%env(CONTAINER_FILESYSTEM_REGION)%"
                endpoint: "%env(CONTAINER_FILESYSTEM_ENDPOINT)%"
                use_path_style_endpoint: true
        theme: *public_bucket
        asset:
            type: local
            url: '%env(APP_URL)%'
            config:
                root: '%kernel.project_dir%/public'
    cdn:
        url: "%env(CONTAINER_FILESYSTEM_PUBLIC_URL)%"
elasticsearch:
    index_settings:
        number_of_replicas: null
        number_of_shards: null
framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(CONTAINER_CACHE_URL)%'
