-   name: app
    stack:
        - "php@8.3":
          extensions:
            - redis
            - amqp
            - sodium
        - mysql80
        - "nodejs@20"
        - "shopware-cli"
    variables:
        env:
            # Tell Shopware to always install in production-mode.
            APP_ENV: prod
            # Instance ID is empty by default, change to something unique in your project
            INSTANCE_ID: ""
            # Enable HTTP Cache to get cache-control headers
            SHOPWARE_HTTP_CACHE_ENABLED: 1
            # Use different redis dbs for cache and sessions
            REDIS_CACHE_DATABASE: 0
            REDIS_SESSION_DATABASE: 2
            # Elasticsearch, see https://developer.shopware.com/docs/guides/hosting/infrastructure/elasticsearch#activating-and-first-time-indexing
            SHOPWARE_ES_ENABLED: 0
            SHOPWARE_ES_INDEXING_ENABLED: 0
            SHOPWARE_ES_INDEX_PREFIX: "sw6"
            # Disables the Shopware web installer
            SHOPWARE_SKIP_WEBINSTALLER: 1
            # Enables the Shopware Composer plugin loader and disables the database plugin loader. All extensions will need to be installed with Composer
            COMPOSER_PLUGIN_LOADER: 1
            COMPOSER_ROOT_VERSION: 1.0.0
        php:
            upload_max_filesize: 32M
            post_max_size: 32M
            memory_limit: 512M
            "zend.assertions": -1
            "opcache.enable_file_override": 1
            "opcache.interned_strings_buffer": 20
            "opcache.validate_timestamps": 0
            "zend.detect_unicode": 0
            realpath_cache_ttl: 3600
            "opcache.memory_consumption": 128M
            "opcache.max_accelerated_files": 20000
    # The hooks that will be performed when the package is deployed.
    hooks:
        build: |
            set -e

            if [ "$PROJECT_ENVIRONMENT_TYPE" = development ]; then
                echo "remove fastly.yaml on environment type development"
                rm -f config/packages/fastly.yaml
            fi

            shopware-cli project ci .

            bin/ci theme:compile
        deploy: |
            set -e

            ./vendor/bin/shopware-deployment-helper run --skip-theme-compile --skip-asset-install

            echo "==================================================="
            echo "UPDATE SALES CHANNEL DOMAIN IF ENVIRONMENT TYPE IS NOT PRODUCTION"
            echo "==================================================="
            # Configure the sales channel domains automatically for non-production environments
            if [ "$PLATFORM_ENVIRONMENT_TYPE" != production ]; then
                export FRONTEND_URL=`echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select(.value.id=="shopware") | .key'`
                export FRONTEND_DOMAIN=`php -r 'echo parse_url($_SERVER["FRONTEND_URL"], PHP_URL_HOST);'`
                bin/console sales-channel:update:domain "$FRONTEND_DOMAIN"
            fi

            echo "==================================================="
            echo "CLEAR CACHES"
            echo "==================================================="
            # run cache clear commands, on grid environments this should run in the deploy hook,
            # on dedicated generation 2, it will run as part of the pre_start hook (to be set up by Platform.sh support)
            if [ -z "$PLATFORM_REGISTRY_NUMBER" ]; then
                sh bin/prestart_cacheclear.sh
            else
                # on dedicated gen 2, we need to explictly clear the redis cache since redis is not available during pre_start
                bin/console cache:pool:clear cache.object
            fi

            echo "==================================================="
            echo "SETUP FASTLY AND CLEAR OPCACHE"
            echo "==================================================="
            if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ] || [ "$PLATFORM_ENVIRONMENT_TYPE" = "stage" ]; then
                if [ -e bin/setup-fastly.sh ]; then
                    echo "Running setup-fastly.sh script"
                    ./bin/setup-fastly.sh
                else
                    echo "setup-fastly.sh script not found"
                fi
            fi

            # Send USR2 signal to php-fpm to clear the opcache
            pkill -f -USR2 -u web php-fpm

    # The relationships of the application with services or other applications.
    # The left-hand side is the name of the relationship as it will be exposed
    # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
    # side is in the form `<service name>:<endpoint name>`.
    relationships:
        database: "db:mysql"
        rediscache: "cacheredis:redis"
        # comment to disable rabbitmq
        rabbitmqqueue: "rabbitmq:rabbitmq"
        # uncomment if you want to use opensearch/elasticsearch
        # opensearch: "opensearch:opensearch"
    # The size of the persistent disk of the application (in MB).
    disk: 2048
    # The mounts that will be performed when the package is deployed.
    mounts:
        "/files":
            source: service
            service: fileshare
            source_path: "files"
        "/public/media":
            source: service
            service: fileshare
            source_path: "public/media"
        "/public/thumbnail":
            source: service
            service: fileshare
            source_path: "public/thumbnail"
        "/config/secrets":
            source: service
            service: fileshare
            source_path: "config/secrets"
        "/var":
            source: service
            service: fileshare
            source_path: "var"
        "/var/cache":
            source: local
            source_path: "var/cache"
        "/.global":
            source: local
            source_path: "global"
        "/.cache":
            source: local
            source_path: ".cache"
    # The configuration of app when it is exposed to the web.
    web:
        locations:
            "/":
                # The public directory of the app, relative to its root.
                root: "public"
                # The front-controller script to send non-static requests to.
                passthru: "/index.php"
                expires: 24h
                rules:
                    \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                        expires: 4w
    workers:
        queue:
            disk: 128
            commands:
                start: |
                    bin/console cache:clear
                    bin/console messenger:consume async,failed --memory-limit=$(cat /run/config.json | jq .info.limits.memory)M --time-limit=295

    crons:
        scheduler:
            spec: '*/5 * * * *'
            cmd: 'php bin/console scheduled-task:run --no-wait'
